# Generated by Django 2.2.7 on 2021-01-07 14:02

import bankapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default=bankapp.models.random_string, max_length=26)),
                ('balance', models.IntegerField(default=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_account', to='bankapp.UserAccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_account', to='bankapp.UserAccount')),
            ],
        ),
    ]
