version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: supersecretpassword
  app:
    build: .
    environment:
      - DEBUG=1
      - DB_PASSWORD=supersecretpassword
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_HOST=db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bankapp
    ports:
      - "8000:8000"
    depends_on:
      - db
